### ISSUE TITLE
Linux Compatibility?

### ISSUE THREAD

**Issue by GabrielZCode** [SebLague/Neural-Network-Experiments#3]
I just imported your code to Unity but on running it just presents me a blue screen with nothing in it.
Its that a problem with C# or .NET? 
The console doesn't give me any errors

![Screenshot_20221021_161608](https://user-images.githubusercontent.com/86977092/197272722-8898d48c-cb7d-4c1a-aeab-6f674d4fa2ec.png)

Anyways , thanks a lot for the learning on your video & code.

**Comment by Airs702** [comment]
same to me, hope for the solution, thanks

**Comment by SebLague** [comment]
Hi, it looks like it has opened a blank scene for some reason. You'll need to navigate to the Scenes folder in the project window, and open one of the scenes from there.
